Import('*')

progs_env.Program(
        target = 'vp-tris',
        source = ['vp-tris.c'],
    )

shaders = env.Glob('*.txt')

for shader in shaders:
    env.Command(
        target = shader,
        source = shader.srcnode(),
        action = [Copy('$TARGET', '$SOURCE')],
    )
